[ESP32C3_SuperMini_sx1276]
extends = esp32_base
board = lolin_c3_mini

build_flags =
  ${esp32_base.build_flags}

  ; === Variant include ===
  -I variants/esp32c3_supermini_sx1276

  ; ===== Board ID =====
  -D ESP32C3_SUPERMINI

  ; ===== LoRa pins =====
  -D P_LORA_NSS=7
  -D P_LORA_SCLK=4
  -D P_LORA_MISO=5
  -D P_LORA_MOSI=6
  -D P_LORA_DIO_0=2
  -D P_LORA_DIO_1=RADIOLIB_NC
  -D P_LORA_RESET=10
  
  ; enable verbose RadioLib debug output for temporary troubleshooting
  ; -D RADIOLIB_DEBUG
  ; -D RADIOLIB_DEBUG_SPI

  ; ===== Radio driver =====
  -D RADIO_CLASS=CustomSX1276
  -D WRAPPER_CLASS=CustomSX1276Wrapper

  ; ===== Radio tuning =====
  -D SX127X_CURRENT_LIMIT=120

  -D LORA_TX_POWER=20

build_src_filter =
  ${esp32_base.build_src_filter}
  +<../variants/esp32c3_supermini_sx1276>

lib_deps =
  ${esp32_base.lib_deps}


[env:ESP32C3_SuperMini_sx1276_companion_radio_usb]
extends = ESP32C3_SuperMini_sx1276

build_flags =
  ${ESP32C3_SuperMini_sx1276.build_flags}
  -I examples/companion_radio/ui-new

  ; Companion configuration
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40

build_src_filter =
  ${ESP32C3_SuperMini_sx1276.build_src_filter}
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>

lib_deps =
  ${ESP32C3_SuperMini_sx1276.lib_deps}
  densaugeo/base64 @ ~1.4.0